version: '3.8'

networks:
  kong-net:
    external: false

services:
  kong:
    image: kong:3.7
    container_name: kong
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    networks:
      - kong-net 
    environment:
      - KONG_DATABASE=off 
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app
    working_dir: /app
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - kong-net